### ISSUE TITLE
Need help understanding column in clustergram

### ISSUE THREAD

**Issue by kwendt3** [brianpenghe/Matlab-genomics#3]
Hi, I'm hoping to understand how the column in Figure 1 was generated in relation to the rest of the data. I'm not entirely sure how the color code responds to the rest of the heatmap.  It looks like a phylogeny tree by organ and I highlighted it in red, but I'm not sure what it means spatially in the context of the differentially expressed genes it sits beside.  We have a similar set of data with different organs, so I want to replicate the figure, but I am wondering how this part of the data was generated. 

![Screen Shot 2021-03-17 at 9 08 18 AM](https://user-images.githubusercontent.com/15107884/111481506-072c6880-8701-11eb-98dd-91548ab85488.png)

**Comment by brianpenghe** [comment]
The colors on the left are actually just highlighting the major clusters, which are identical to the ones in the blue box (see below). But you probably have to manually color the dendrogram by right clicking on the nodes and selecting colors.
The colors in the blue box can be generated following [these codes](https://github.com/brianpenghe/Matlab-genomics/blob/master/He_2020_ENCODE3_RNA/Notebook_1_BulkRNA.md#add-group-labels) 
![Untitled](https://user-images.githubusercontent.com/4110443/111814407-54136900-88d2-11eb-9a20-cc390c6c1326.png)
Hope that helps.
